### ISSUE TITLE
Change delimiter / separator

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#148]
_Currently ""."" is used as a delimiter for decimal places and ',' is used as a thousands separator. 
For german language settings it should be the other way around, meaning 3000 = 3.000 and 1/2 = 0,5_

_Our suggestion would be to distinguish both options according to the selected browser language setting to guarantee that Austrian users get the right presentation._

To keep all the UI consistent, we need to use the same decimal separator for not editable numbers (e.g. coordinate picker, counters …) and inputs. This means that the number input should be all synchronized with the current language selected by the user, as well as the numbers labels (not editable) that are actually shown in the whole UI.

To allow this we have to develop:
 
* A custom input tool that works as the native one by allowing to insert only numbers, correct separators and simulates the native one (some libs exists, but an initial investigation didn’t have good results in terms of compatibility so probably the component may need to be developed from scratch)

* Replace the new Number field wherever a number input is required: 
  - Research and review
  - Integration and eventual adapters

**Comment by dsuren1** [comment]
Moved back to suggest a new solution as per PR review comment.
https://github.com/geosolutions-it/MapStore2/pull/5215#issuecomment-629987766

**Comment by ElenaGallo** [comment]
@dsuren1 some notes after testing this issue:

- [ ] With the English translation the BBox bookmark has a decimalSeparator with "," instead of "."
![1](https://user-images.githubusercontent.com/56537133/94711515-82af7e80-0348-11eb-89f3-22370a01ee5f.JPG)

*How to reproduce*
- Open a map
- Click on settings
- Change translation to English
- Click on Change the search tool
- Click on Search by bookmark
- Click on Bookmark settings
- Click on Add
- Click on Use current view as BBox

- [ ] With the Deutsch traslation the Chart Widget has decimalSeparator with "." insted of ","
![2](https://user-images.githubusercontent.com/56537133/94711655-ab377880-0348-11eb-8de2-3180957f9090.JPG)

*How to reproduce*
- Open [this](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/115) map
- Click on settings
- Change translation to Deutsch

**Current result**
The values on the y axis have decimalSeparator with "." insted of ","

- [ ] With the Deutsch traslation the Filter layer has thousandSeparator with "," insted of "." and the Layer filter does not work.
![3](https://user-images.githubusercontent.com/56537133/94711657-aecaff80-0348-11eb-9190-b39319cff9d8.JPG)

*How to reproduce*
- Open [this](https://austrocontrol.geo-solutions.it/austrocontrol-ms2/#/viewer/openlayers/115) map
- Click on settings
- Change translation to Deutsch
- Click on TOC
- Select the layer
- Click on Filter layer
- Click on Add condition
- Add: PERSONS > 5225445

**Comment by dsuren1** [comment]
@tdipisa @ElenaGallo 
Issue 1 - Bookmark change was deployed before this change so it doesn't have this implementation. I will add it.
Issue 2 & 3 - Not part of this change. As this change targets only the input field of 'type=number' to be localized

**Comment by dsuren1** [comment]
Note: Kindly test issue 1 reported above after this PR is merged with master
https://github.com/geosolutions-it/MapStore2/issues/5960
