### ISSUE TITLE
Drop Down for different map views

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#152]
It shall be possible to switch between different views (based on bbox function - https://mapstore.readthedocs.io/en/latest/user-guide/share/) directly in the map.
For this reason there shall be a drop down list left to the search bar. Whenever a drop down element is selected the map shall be opened at the specified bbox.

a) The entries for the drop down list shall be configurable by the administrator only and there shall be a configuration button similar to the one for search services, but only visible to the administrator.
b) The administrator shall be able to set a name for the drop down list entry.
c) The administrator shall have two options to set a bbox: 1) manually by entering coordinates and 2) automatically get bbox parameters from the current view.
d) The administrator shall have a choice between the following settings
     1) when a list entry is chosen the respective bbox shall be loaded and the visibility of the layers shall be reloaded as defined in the map configuration file and 
     2) when a list entry is chosen the respective bbox shall be loaded and the visibility of the layers shall be kept as currently (at the moment of the list entry selection) set by the user  for each entry.
e) all settings shall be stored in the map configuration file

In our case the function shall be used to link different aerodrome maps. Data for all aerodromes in Austria shall be published in one map, but the user shall have the possibility to directly zoom to the desired aerodrome by one click.

**Comment by tdipisa** [comment]
Mockup available [here](https://demo.geo-solutions.it/mockups/mapstore2/get-feature-info-annotations/#/) (see Search Tool changes)

**Comment by allyoucanmap** [comment]
Some notes and proposals on the Search Plugin changes:

### 1) Menu items entries
Currently we have a menu list with 2 search tool and a entry for configuration related to first tool. 
![image](https://user-images.githubusercontent.com/19175505/81541767-ed4d2700-9373-11ea-98a4-293c70746bb6.png)

We should remove the configuration entry an make it more ralted to the first search tool.
![image](https://user-images.githubusercontent.com/19175505/81541814-fe963380-9373-11ea-89a4-b1c79eaf6c55.png)


### 2) Search Plugin Structure

Search plugin needs some reviews in particular the remove of [HelpWrapper](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/Search.jsx#L277) (*)and replace of `span` wrappper with `div`. These changes could effect the current css/less but could help to clean up useless or repated css rules. Expected structure:

![image](https://user-images.githubusercontent.com/19175505/81538960-c5f45b00-936f-11ea-80bd-5cd57eac76bc.png)

(*) The HelpWrapper is a plugin not used anymore because replaced by Tutorial

Search types:

Note 1: Loader for search by location name is inside the toolbar and can be enable with the `loading` props for the search button.

Note 2: Styles of coordinates are aligned with changes needed in #155

![image](https://user-images.githubusercontent.com/19175505/81539667-e1139a80-9370-11ea-82e8-19e53b859721.png)

### 2) New Search Tool as Plugin? (Proposal)

We could improve the Search plugin to be able to contain new search tools using the ability of MapStore to assign containers to a single plugin.

![image](https://user-images.githubusercontent.com/19175505/81540366-d9082a80-9371-11ea-8ed0-1949a5b7e950.png)

The new plugin should be configured as follow:

eg:

```js
import React from 'react';
import { Glyphicon, MenuItem } from 'react-bootstrap';
import { createPlugin } from '../utils/PluginsUtils';
import { connect } from 'react-redux';
import { createSelector } from 'reselect';
import { changeActiveSearchTool } from "../actions/search";

function SearchByBookmarkPlugin({
    active,
    togglable
}) {

    const searchTool = (
        <div>
            {/* implementation */}
        </div>
    );

    if (!togglable) {
        return searchTool;
    }

    return active
        ? searchTool
        : null;
}

const selector = createSelector([
    state => state?.search?.activeSearchTool || null
], (activeSearchTool) => ({
    active: activeSearchTool === 'searchByBookmark'
}));

const SearchMenuItem = ({ active, eventKey, onClick }) => (
    <MenuItem
        key={eventKey}
        active={active}
        eventKey={eventKey}
        onClick={() => onClick('searchByBookmark')} >
        <Glyphicon glyph="bookmark"/>
        Search by Bookmark
    </MenuItem>
);

export default createPlugin('SearchByBookmark', {
    component: connect(selector)(SearchByBookmarkPlugin),
    containers: {
        Search: {
            priority: 1,
            menuItem: connect(selector, {
                onClick: changeActiveSearchTool
            })(SearchMenuItem)
        }
    }
});

```

With this configuration:

```js
...
containers: {
    Search: {
        priority: 1,
        menuItem: connect(selector, {
            onClick: changeActiveSearchTool
        })(SearchMenuItem)
    }
}
...
```

the Search plugin will get the SearchByBookmarkPlugin `component` and `menuItem` inside the `items` props and with improvements it can be able to locate the tools and the menuItem in the right position.

**Comment by MV88** [comment]
@dsuren1 @allyoucanmap @tdipisa 
Which solutions has been choosen, so i can do a proper review?

**Comment by tdipisa** [comment]
Waiting the merge of  https://github.com/geosolutions-it/MapStore2/pull/5784 for a fix.
