### ISSUE TITLE
Order of GFI

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#155]
Currently the order of GFI when multiple features are affected by one click is switched randomly and it is not clear how the behavior can be influenced.

a) The order of the GFI shall be based on the layer sorting in the TOC, meaning top entry in the TOC shall be the first GFI to appear.

**Comment by tdipisa** [comment]
Mockup available [here](https://demo.geo-solutions.it/mockups/mapstore2/get-feature-info-annotations/#/) (see changes in GFI)

**Comment by dsuren1** [comment]
- All layers will be sorted as in TOC
- The first element that comes will be selected (and enabled)

> Invisible levels will not appear in the list 

- _Hidden layers will not be listed in layer selector_

> While an Identify request is performed, all the visible layer in the layer selector are disabled at the beginning
- _Initially, all the layers in layer selector are disabled which will prevent the user from selecting a layer for which the requested has not been completed._

> While loading the other elements of the list (sorted as in TOC) will start enabling.

- _The other layers will be enabled as their respective requests get completed_

> If a layer responded with no-content, the selection will be anyway allowed.

- _The layer request completes with no feature as a response or with an error, the layer will be enabled and available for selection from layer selector (drop-down), and "There is no information available for this point" message will be displayed in the Viewer panel._

> The selector should look more or less like the one provided with an arrow (drop-down menu) instead of a burger menu

- _The layer selector will be a drop-down with an arrow, as provided in the mockup._

@tdipisa  Kindly let me know if my understanding is clear

**Clarification:**
In the mockup, the GFI panel title is empty, since the layer name will be in the drop-down. In this case, can I add a title called "**Feature Info**" or just leave it as in mockup?

![2020-06-03 19_24_29-DevTools - demo geo-solutions it_mockups_mapstore2_get-feature-info-annotations_](https://user-images.githubusercontent.com/26929983/83645906-a4823a00-a5d0-11ea-992a-9238809fc7ec.jpg)

**Comment by tdipisa** [comment]
@dsuren1 ok, please proceed.
Regarding the one below

>Clarification:
In the mockup, the GFI panel title is empty, since the layer name will be in the drop-down. Is this fine?

Respect the mockup

**Comment by tdipisa** [comment]
@offtherailz with the current implementation the first element for which we receive a response from the server is enabled and visualized even though there are not content for it in the Identify response.
I think that it is quite confusing for the user and for this reason it is better to enable the first element for which we receive a response with some content inside to show. Which is your opinion?

**Comment by offtherailz** [comment]
Agree. The list have to be full, with the elements ordered as for the TOC, and with selected the first element that provided a response. The entries that does have a response, disabled (an improve to the mock-up is to not allow selection at all for disabled entries).

**Comment by tdipisa** [comment]
@dsuren1 moving back this issue in ready. Please do what we agreed in the call and simply enable first the first element for which we receive a response with some content inside, leave the other implemented parts as they are now.

**Comment by dsuren1** [comment]
> @dsuren1 moving back this issue in ready. Please do what we agreed in the call and simply enable first the first element for which we receive a response with some content inside, leave the other implemented parts as they are now.

The issue fix is given as part of the PR https://github.com/geosolutions-it/MapStore2/pull/5787
Corresponding issue in Mapstore: https://github.com/geosolutions-it/MapStore2/issues/5773
