### ISSUE TITLE
Responsive Design - Info Box - Update of the WYSIWYG

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#162]
Update of the WYSIWYG used by the current Details tool to allow aligning and resizing images.

Use the new WYSIWYG editor implemented for Stories (draftJS editor). This means not only adapting the new Text editor to the existing Details tool, but also readapting it in order to include and manage additional utilities to allow operations on images, that are available only using the new WYSIWYG (the [Image](https://www.draft-js-plugins.com/plugin/image) and other plugins that allows to align images, **_the example Alignment + Resize + Focus + Drag’n’drop_** seems near to the desired behaviour). The most part of the estimate reported in the tasklist is needed to accomplish this specific task.

![image](https://user-images.githubusercontent.com/1280027/77438252-debba800-6de5-11ea-8fec-fe6920afb6f6.png)

**Comment by ElenaGallo** [comment]
Blocked by #160

**Comment by ElenaGallo** [comment]
- [ ] Cannot Center, Resize and Drag’n’drop the image on the detail page
![o 2](https://user-images.githubusercontent.com/56537133/95354823-2b1f8e80-08c5-11eb-8c4f-67be2f7d1cd4.gif)

**How to Reproduce**

- Open a map
- On Burger Menu open the Save as 
- Click on Add Detail
- Enter an image
- Click on Add
- Click on C button under the image

*Current result**
You can Center, Resize and Drag’n’drop the image on the detail page 

- [ ] After being saved, the resized image, returns to its original size
![3](https://user-images.githubusercontent.com/56537133/95354852-31ae0600-08c5-11eb-95a5-a7e785a99451.gif)

**How to Reproduce**

- Open a map
- On Burger Menu open the Save as 
- Click on Add Detail
- Enter an image
- Canghe the size
- Click on Add
- Click on Save

*Current result**
On modal, the image size is not what has been set

- [ ] If the detail has an image, expanding the modal the top bar is cut off
![1](https://user-images.githubusercontent.com/56537133/95354882-3a064100-08c5-11eb-937e-2982e7fa5c83.JPG)

**How to Reproduce**

- Open a map
- On Burger Menu open the Save as 
- Click on Add Detail
- Enter an image
- Click on Add
- Click on Save
- Click on Show as modal
- Click on Save
- On Burger Menu open the Aboaut this map
- Click on Expand the modal

*Current result**
The top bar is cat off

**Comment by offtherailz** [comment]
During the evaluation of this task we where evaluating to use [DraftJS](https://draftjs.org/) with the plugin [image](https://www.draft-js-plugins.com/plugin/image) linked

MapStore introduced for GeoStory this library [react-draft-wysiwyg](https://github.com/jpuri/react-draft-wysiwyg), that uses internally DraftJS and provides a different image tool. 
Including the plugin "image" inside the library used is not feasable without custimizing the lib itself.
During MapStore development, we forked react-draft-wysiwyg to customize link tool in order to provide a way to create custom links actions. So we need to evaluate how much does it takes to use the plugin image (or the alignment system of it, that looks better) maintaining the existing tool in the toolbar, that is anyway good, with a lot of features.

**Comment by tdipisa** [comment]
Closed in favor of https://github.com/geosolutions-it/MapStore2/issues/6120
