### ISSUE TITLE
Client ID 9 - Selection of mulitple GFI in window

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#232]
(a) Layer without GFI (which do not intersect with clicked point in map) shall not be shown in the dropdown list.

**Comment by tdipisa** [comment]
>(a) Layer without GFI (which do not intersect with clicked point in map) shall not be shown in the dropdown list.

We have to check this.

**Comment by tdipisa** [comment]
Dear @michegg, we have implemented this functionality as we agreed [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/155#issuecomment-603252274). In particular point number 5 says (it is also present in the tech proposal):

>If a layer responded with no-content, the selection will be anyway allowed.

**Comment by michegg** [comment]
@tdipisa The comment you're quoting refers to **Client ID 8**. We accepted this, because it was argued that this is necessary to other customers and due to the fact, that under _settings_ an option "_Show empty results message in GetFeatureInfo panel_" exists.
Currently, whenever the option is deselected, all GFI entries without result are removed from the list. Therefore you changed this behavior.


Nevertehless **Client ID 9** clearly refines our requirements, while there is no comment, that point (a) will not be entirely fulfilled.
Fulfillment of point (a) is absolutely necessary to us.

**Comment by tdipisa** [comment]
@michegg both issues (#165 and #155) are connected since they are referring to the same tool. What reported [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/155#issuecomment-603252274) is what we agreed during the initial KO in GeoSolutions. Since the point below:

>If a layer responded with no-content, the selection will be anyway allowed.

mentions that also in case of no contents the selection in the drop down must be allowed, we have changed the previous behavior where only layers with Info present in the clicked point were available in the Identify panel. Is that probably a misunderstanding?

Anyway, I will ask developers to check if we can revert that particular bheavior. 

Therefore, if I understood correcly, layers with no contents in the clicked point must be available in the drop down list only if the option "Show empty results message in GetFeatureInfo panel" is checked in Settings? Is that correct?

![image](https://user-images.githubusercontent.com/1280027/100720992-117b5e80-33bf-11eb-883a-fb82519a7cea.png)

**Comment by michegg** [comment]
> @michegg both issues (#165 and #155) are connected since they are referring to the same tool. What reported [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/155#issuecomment-603252274) is what we agreed during the initial KO in GeoSolutions. Since the point below:
> 
> > If a layer responded with no-content, the selection will be anyway allowed.
> 
> mentions that also in case of no contents the selection in the drop down must be allowed, we have changed the previous behavior where only layers with Info present in the clicked point were available in the Identify panel. Is that probably a misunderstanding?

Yes, it kind of must be. We never requested such a change.
> 
> Anyway, I will ask developers to check if we can revert that particular bheavior.
> 
> Therefore, if I understood correcly, layers with no contents in the clicked point must be available in the drop down list only if the option "Show empty results message in GetFeatureInfo panel" is checked in Settings? Is that correct?

Yes, that's correct. Since we provide a lot of layers it is crucial to us, that the user doesn't get overwhelmed with too much unnecessary information (--> "Show empty res..." function was a requirement made by us approx. two years ago).

**Comment by tdipisa** [comment]
@dsuren1 as per @michegg feedback [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/232#issuecomment-736550078) you can proceed as reported [here](https://github.com/geosolutions-it/austrocontrol-C125/issues/232#issuecomment-736339983)
