### ISSUE TITLE
Client ID 12 - Set symbols as default

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#235]
doesn't work with provided parameters. Please provide information on how and where to set parameters in localConfig

**Comment by tdipisa** [comment]
> doesn't work with provided parameters. Please provide information on how and where to set parameters in localConfig

Ok, we will check if all is fine/updated in our plugin documentation to get back to you.

**Comment by dsuren1** [comment]
Documentation for Annotation plugin is available [here ](https://dev.mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Annotations)

Kindly try this config to set the symbol default parameters in localConfig
```
{
  "desktop": [
    ...,
    {
      "name": "Annotations",
      "cfg": {
        "symbolsPath": "assets/symbols/",
        "defaultShape": "MIL",
        "defaultShapeFillColor": "#417505",
        "defaultShapeSize": 40,
        "defaultShapeStrokeColor": "#f8e71c"
      }
    },
    ...
  ]
}
```
**Result for the above config**
![2020-11-24 19_31_12-Settings](https://user-images.githubusercontent.com/26929983/100105450-63872600-2e8d-11eb-9762-db5306026c04.jpg)

**Comment by michegg** [comment]
Thanks, configuration works for standard definition of symbol style.

What we are missing is how to set symbols as default type instead of markers, as described in our requirements:
"_**It shall be possible for the admin to set symbols as the default type for point annotations (currently it's markers**) and to define size and color of the default symbol._"

Our suggestion was to use a parameter similar to `"defaultPointType": "symbol"` e.g. in the InitialState config for annotations.

**Comment by dsuren1** [comment]
@michegg This seems to be a bug. We will let you know once it's ready for testing.
