### ISSUE TITLE
Client ID 27 - Annotations on/off indiviudally

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#246]
- Visibilty of Layer ""Annotations"" (TOC) is not syncronised with Annotation editor (right panel) --> confusion for user. E.g. Create Annotations. Set Layer ""Annotations"" invisble in ToC. Annotation in Annoation window on right side are still indicated as visible (open eye), but it is not possible to show them, because Layer in ToC is invisible.Maybe it would be better to completly remove the Annotation Layer in ToC as it is now possible to show/hide Annotations individually.

- (c) it is not possible to hide/show all annoations at once via annotations window on right side.

- When editing one Anntoation all other annotations are invisble --> think we already discussed this one. Why is it done? Where is the advantage?

**Comment by tdipisa** [comment]
> Visibilty of Layer ""Annotations"" (TOC) is not syncronised with Annotation editor (right panel) --> confusion for user. E.g. Create Annotations. Set Layer ""Annotations"" invisble in ToC. Annotation in Annoation window on right side are still indicated as visible (open eye), but it is not possible to show them, because Layer in ToC is invisible.Maybe it would be better to completly remove the Annotation Layer in ToC as it is now possible to show/hide Annotations individually.

This is not a requirement but I think it is better to do it by including a sync between the two, for example: 

- As soon as I hide all annotations in the annotation panel, also the layer in TOC changes his state. 
- If then I show one annotation in the annotation panel, also the layer in TOC changes his state accordingly
- As soon as  I hide the annotation layer in TOC all the annotations are hidden accordingly

>(c) it is not possible to hide/show all annoations at once via annotations window on right side.

Since there is the requirement **d)** we have kept that, no need to duplicate things.

**Comment by michegg** [comment]
Sync is ok as described by you.
If c) is not needed because of d)  (although the requirement was to include the function into the annotations window), then synchronizing layer and annotation list must be a requirement, as it is necessary to give the user a correct feedback about the status of annotations. Also it's an inconsistency between two functions within MapStore.

Yes, it's no requirement. Still it would be useful to give the user the possibility to see other annotations in case they are drawing based in other annotations. Probably we will come back to this.
