### ISSUE TITLE
Measurement tool issues

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#268]
When adding a new vertex via the + button:

- [x] **Segment measurement:** until the new vertex is changed to other coordinates than 0 lat 0 lon, the value for all segments is replaced by the length of the whole line. Sometimes after applying the coordinate changes, values are switched back to correct measurements (see video measue1.mp4).

https://images.zenhubusercontent.com/111421835/45debbad-4820-498b-b0ac-54112239e783/measure1.mp4

But it also happens that they remain incorrect and are even mixed up with area measurements (see video meaure3.mp4)

https://images.zenhubusercontent.com/111421835/b43757df-35b2-4aeb-bd84-a9606f855d96/measure3.mp4

- [x] **Area measurement:** until the new vertex is changed to other coordinates than 0 lat 0 lon, all segment measurements are removed. After applying the coordinate changes a vertex equal to the first one in the vertex list, is automatically added. Also when changing one of the existing vertices, a new vertex, equal to the first one in the vertex list, is automatically added (see video measure1.mp4 above)

- [x] After switching between different measure options (e.g. segment vs. area) MapStore crashes (see videos measure2.mp4 and measure3.mp4 above)

https://images.zenhubusercontent.com/111421835/66a5fd76-313e-4ccc-bc7b-c0bdde9da0f2/measure2.mp4

- [x] There is a minor graphical issue, when using aeronautical coordinates. Input fields only use approx. half of the available space

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/83fadc88-ff8c-485d-b5ed-f7315fb8de83)

**Comment by dsuren1** [comment]
**Note**
To address the issue with displaying the labels and also make it in sync with the changes done on the coordinates editor, we will do the following.
1. When user clicks the **+** sign to add a new coordinate
2. The segment length _labels_ are **retained** for the _existing valid coordinate rows_ and **empty label** will be displayed between the last valid coordinates row and the newly added coordinates row
3. Then, disable any updates to other coordinates row, except for the new empty coordinates row. We achieve this by **disabling** the _drag icon, coordinate fields, delete button on other rows, geometry icon, drop down (to select feature) and units drop down_
3. As soon as the user enters a valid coordinates and hit the **tick** (submit) icon, the length between the coordinates are properly calculated and the segment labels are displayed
4. Further, all the disabled elements are enabled again for modification.

**Comment by tdipisa** [comment]
@dsuren1 I've tested your updates using this context and I found the following to fix:

- [ ] As soon as you create a second annotation of the same type it is no longer selected inside the dropdown (it is a regression introduced by your update)

- [ ] Clicking on + button we should also disable the map interaction, now you can draw another measurement and it can be confusing for the user

- [ ] connected to point 2. Instead of allowing the draw of a new annotation in this case we can allow the user to click on map to fill the coordinate fields

**Comment by michegg** [comment]
@tobia @dsuren1 I just did a test on our environment and came across an issue, that is also present in your installation [here](https://dev.mapstore2.geo-solutions.it/mapstore/#/context/c125_austrocontrol).

- There are problems when using the digit "0" in decimal places of a coordinate.
E.g. go to distance measuring tool. Try to measure distance from lat: 47.242902 lon: 10.403016 to lat: 48.222 lon: 14.301 by entering the values manually.
**Mapstore will ignore all entered 0 values for decimal places.**
- It is possible to enter the "0" when editing the coordinate, but after adding or changing any digit the cursor will always jump to the end of the input field, disabling the possibility to change another digit by using the arrow keys on the keyboard. The user will have to use the mouse to click on a specific position in order to change another digit. After doing so the cursor will again be placed at the end of the input field.

**Both behaviors are also present for annotation creation, GFI coordinate editor and in the sharing window.**

**Comment by tobia** [comment]
@michegg I think you mentioned me by mistake?

**Comment by tdipisa** [comment]
@tobia yes, sorry about that.

**Comment by michegg** [comment]
@tobia yes, sorry
@tdipisa thanks for correcting

**Comment by tdipisa** [comment]
@michegg I've opened a [separate issue](https://github.com/geosolutions-it/austrocontrol-C125/issues/269) for the [above comment](https://github.com/geosolutions-it/austrocontrol-C125/issues/268#issuecomment-781383659).
