### ISSUE TITLE
Some issues with coordinate input fields in Measurement and Annotation tools

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/austrocontrol-C125#269]
Below what reported by @michegg in [this issue](https://github.com/geosolutions-it/austrocontrol-C125/issues/268#issuecomment-781383659).

>@tdipisa @dsuren1 I just did a test on our environment and came across an issue, that is also present in your installation here.

>- There are problems when using the digit "0" in decimal places of a coordinate.
E.g. go to distance measuring tool. Try to measure distance from lat: 47.242902 lon: 10.403016 to lat: 48.222 lon: 14.301 by entering the values manually.
**Mapstore will ignore all entered 0 values for decimal places.**
>- It is possible to enter the "0" when editing the coordinate, but after adding or changing any digit the cursor will always jump to the end of the input field, disabling the possibility to change another digit by using the arrow keys on the keyboard. The user will have to use the mouse to click on a specific position in order to change another digit. After doing so the cursor will again be placed at the end of the input field.

>**Both behaviors are also present for annotation creation, GFI coordinate editor and in the sharing window.**

**Comment by dsuren1** [comment]
> * There are problems when using the digit "0" in decimal places of a coordinate.
>   E.g. go to distance measuring tool. Try to measure distance from lat: 47.242902 lon: 10.403016 to lat: 48.222 lon: 14.301 by entering the values manually.
>   **Mapstore will ignore all entered 0 values for decimal places.**

_This is because the coordinates field being used is not a native input field but custom one modified with the implementation of the **react-numeric-input** library, to act as a localized input field. Due to this reason, as we type/input, it parses the input value, formats it with the localization data (EN, DE, ..etc) followed by conversion of data to be displayed in the field, we lose the trailing zero only that comes after the decimal place._ 


> * It is possible to enter the "0" when editing the coordinate, but after adding or changing any digit the cursor will always jump to the end of the input field, disabling the possibility to change another digit by using the arrow keys on the keyboard. The user will have to use the mouse to click on a specific position in order to change another digit. After doing so the cursor will again be placed at the end of the input field.

_This should be fixed and available as part of the measurement tool enhancement. After which we should be able to use left/right arrows to move the cursor position on the coordinate editor fields to modify the input value._
