### ISSUE TITLE
SampleExtension plugin 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/austrocontrol-C125#303]
It is not possible to install the SampleExtension plugin on a context

Error on console: 
> POST https://austrocontrol.geo-solutions.it/austrocontrol-ms2/rest/config/uploadPlugin 500

**How to Reproduce**
- Click on New Context
- Navigate the wizard until step three
- Click on Add an extension
- Add an [SampleExtension](https://app.zenhub.com/files/111421835/689b8830-e968-441c-9ac1-94dd93323959/download)
- Click on Install

##Other useful information

Ref test on cucumber: https://studio.cucumber.io/projects/292756/test-runs/710295/folder-snapshots/7397818/scenario-snapshots/26123903/test-snapshots/35589425

**Comment by taba90** [comment]
@tdipisa the usual dependency conflict issue:
- mapstore services declare this dependency:
  ```
 <dependency>
        <groupId>com.github.java-json-tools</groupId>
        <artifactId>json-patch</artifactId>
        <version>1.12</version>
    </dependency>
```
which transitively uses jackson 2.10.2 dependencies.

- the rest of project uses 2.13.1 which expects the method readCapabilities() of JsonParser to be there.
- the 2.10.2 might be picked up causing a NoSuchMethod error.

To check this is the issue in the WEB-INF lib folder of the austroncontrol installation you should see jackson 2.10.2 jars along the 2.13.1 ones. To fix this I guess excluding the dependency should be enough. 
One word of caution about this: currently inside the mapstore project there is no code path issuing the usage of the dependency transitively importing the jackson 2.10.2. This poses some problem since it would be good as well to test that the dependency with excluded jar still works properly after the exclusion.
Can it be that there is some downstream project entering that code path? The Rest endpoint in question is the load asset where the readResource method can be called with [read patch resource value](https://github.com/geosolutions-it/MapStore2/blob/2f834d40682e6011442b306d694f8098c2f9fb84/java/services/src/main/java/it/geosolutions/mapstore/controllers/extensions/ExtensionsController.java#L53) always set to empty.

**Comment by randomorder** [comment]
please ask Luca Pasquali @tdipisa

**Comment by lpasquali** [comment]
hello @randomorder I added ssh keys for @taba90 and @tdipisa

**Comment by lpasquali** [comment]
updated documentation at the end with commands to restart nginx and mapstore https://docs.google.com/document/d/1K2gObUSUWRJRj_-WJtYMJDT1ZVjDSp6v/edit#

**Comment by tdipisa** [comment]
Thank you so much @lpasquali

**Comment by taba90** [comment]
@tdipisa  opend pr https://github.com/geosolutions-it/austrocontrol-C125/pull/304

**Comment by tdipisa** [comment]
@taba90 merged. let's wait for the jenkins build

**Comment by tdipisa** [comment]
@taba90 the build completed successfully and it is possible to install the sample extension now. I think for this further test we have to apply the fix also on MS master where we have the data directory

>The Rest endpoint in question is the "/load/{resource}" when a json patch is applied. I miss the functional knowledge about this operation. Can I have a front-end guy testing it?

right @offtherailz?

**Comment by tdipisa** [comment]
@taba90 I think you can contribute the dependency enhancement in MS for release 2022.02.01. Thank you.

**Comment by taba90** [comment]
@tdipisa open a pr on master https://github.com/geosolutions-it/MapStore2/pull/8764.
One note: in this case the modification implies the mapstore-services pom only because mapstore doesn't have a root pom like downstream project

**Comment by tdipisa** [comment]
connected the issue and milestone. @offtherailz requested you for a quick double check.

**Comment by taba90** [comment]
backport pr here https://github.com/geosolutions-it/MapStore2/pull/8769

**Comment by tdipisa** [comment]
@ElenaGallo can you please retest and close the issue if all is now working properly? Thank  you.
